// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ShortUrl struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	Code        string
	OriginalUrl string
	Clicks      sql.NullInt32
}
