// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ShortUrl struct {
	ID          uuid.UUID     `json:"id"`
	CreatedAt   time.Time     `json:"created_at"`
	Code        string        `json:"code"`
	OriginalUrl string        `json:"original_url"`
	Clicks      sql.NullInt32 `json:"clicks"`
}
