// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shortUrls.sql

package repository

import (
	"context"
	"database/sql"
)

const createShortUrl = `-- name: CreateShortUrl :one
INSERT INTO short_urls (id, created_at, code, original_url, clicks)
VALUES (
  gen_random_id(),
  NOW(),
  $1,
  $2,
  0
)
RETURNING id, created_at, code, original_url, clicks
`

type CreateShortUrlParams struct {
	Code        string `json:"code"`
	OriginalUrl string `json:"original_url"`
}

func (q *Queries) CreateShortUrl(ctx context.Context, arg CreateShortUrlParams) (ShortUrl, error) {
	row := q.db.QueryRowContext(ctx, createShortUrl, arg.Code, arg.OriginalUrl)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Code,
		&i.OriginalUrl,
		&i.Clicks,
	)
	return i, err
}

const deleteByCode = `-- name: DeleteByCode :exec
DELETE FROM short_urls
WHERE code = $1
`

func (q *Queries) DeleteByCode(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deleteByCode, code)
	return err
}

const getByCode = `-- name: GetByCode :one
SELECT id, created_at, code, original_url, clicks
FROM short_urls
WHERE code = $1
`

func (q *Queries) GetByCode(ctx context.Context, code string) (ShortUrl, error) {
	row := q.db.QueryRowContext(ctx, getByCode, code)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Code,
		&i.OriginalUrl,
		&i.Clicks,
	)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE short_urls
SET clicks = $2
WHERE code = $1
`

type IncrementClicksParams struct {
	Code   string        `json:"code"`
	Clicks sql.NullInt32 `json:"clicks"`
}

func (q *Queries) IncrementClicks(ctx context.Context, arg IncrementClicksParams) error {
	_, err := q.db.ExecContext(ctx, incrementClicks, arg.Code, arg.Clicks)
	return err
}

const listAllFiltered = `-- name: ListAllFiltered :many
SELECT id, created_at, code, original_url, clicks
FROM short_urls
WHERE original_url LIKE $1
ORDER BY created_at ASC
`

func (q *Queries) ListAllFiltered(ctx context.Context, originalUrl string) ([]ShortUrl, error) {
	rows, err := q.db.QueryContext(ctx, listAllFiltered, originalUrl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShortUrl
	for rows.Next() {
		var i ShortUrl
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Code,
			&i.OriginalUrl,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUnfiltered = `-- name: ListAllUnfiltered :many
SELECT id, created_at, code, original_url, clicks
FROM short_urls
ORDER BY created_at ASC
`

func (q *Queries) ListAllUnfiltered(ctx context.Context) ([]ShortUrl, error) {
	rows, err := q.db.QueryContext(ctx, listAllUnfiltered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShortUrl
	for rows.Next() {
		var i ShortUrl
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Code,
			&i.OriginalUrl,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSomeFiltered = `-- name: ListSomeFiltered :many
SELECT id, created_at, code, original_url, clicks
FROM short_urls
WHERE original_url LIKE $3
ORDER BY created_at ASC
OFFSET $1
LIMIT $2
`

type ListSomeFilteredParams struct {
	Offset      int32  `json:"offset"`
	Limit       int32  `json:"limit"`
	OriginalUrl string `json:"original_url"`
}

func (q *Queries) ListSomeFiltered(ctx context.Context, arg ListSomeFilteredParams) ([]ShortUrl, error) {
	rows, err := q.db.QueryContext(ctx, listSomeFiltered, arg.Offset, arg.Limit, arg.OriginalUrl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShortUrl
	for rows.Next() {
		var i ShortUrl
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Code,
			&i.OriginalUrl,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSomeUnfiltered = `-- name: ListSomeUnfiltered :many
SELECT id, created_at, code, original_url, clicks
FROM short_urls
ORDER BY created_at ASC
OFFSET $1
LIMIT $2
`

type ListSomeUnfilteredParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListSomeUnfiltered(ctx context.Context, arg ListSomeUnfilteredParams) ([]ShortUrl, error) {
	rows, err := q.db.QueryContext(ctx, listSomeUnfiltered, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShortUrl
	for rows.Next() {
		var i ShortUrl
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Code,
			&i.OriginalUrl,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
