// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shortUrls.sql

package repository

import (
	"context"
)

const amount = `-- name: Amount :one
SELECT COUNT(id)
FROM short_urls
`

func (q *Queries) Amount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, amount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShortUrl = `-- name: CreateShortUrl :one
INSERT INTO short_urls (id, created_at, code, original_url, clicks)
VALUES (
  gen_random_uuid(),
  NOW(),
  $1,
  $2,
  0
)
RETURNING id, created_at, code, original_url, clicks
`

type CreateShortUrlParams struct {
	Code        string
	OriginalUrl string
}

func (q *Queries) CreateShortUrl(ctx context.Context, arg CreateShortUrlParams) (ShortUrl, error) {
	row := q.db.QueryRowContext(ctx, createShortUrl, arg.Code, arg.OriginalUrl)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Code,
		&i.OriginalUrl,
		&i.Clicks,
	)
	return i, err
}

const deleteByCode = `-- name: DeleteByCode :exec
DELETE FROM short_urls
WHERE code = $1
`

func (q *Queries) DeleteByCode(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deleteByCode, code)
	return err
}

const getByCode = `-- name: GetByCode :one
SELECT id, created_at, code, original_url, clicks
FROM short_urls
WHERE code = $1
`

func (q *Queries) GetByCode(ctx context.Context, code string) (ShortUrl, error) {
	row := q.db.QueryRowContext(ctx, getByCode, code)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Code,
		&i.OriginalUrl,
		&i.Clicks,
	)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE short_urls
SET clicks = $2
WHERE code = $1
`

type IncrementClicksParams struct {
	Code   string
	Clicks int32
}

func (q *Queries) IncrementClicks(ctx context.Context, arg IncrementClicksParams) error {
	_, err := q.db.ExecContext(ctx, incrementClicks, arg.Code, arg.Clicks)
	return err
}

const list = `-- name: List :many
SELECT id, created_at, code, original_url, clicks
FROM short_urls
ORDER BY created_at ASC
OFFSET $1
LIMIT $2
`

type ListParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]ShortUrl, error) {
	rows, err := q.db.QueryContext(ctx, list, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShortUrl
	for rows.Next() {
		var i ShortUrl
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Code,
			&i.OriginalUrl,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const search = `-- name: Search :many
SELECT id, created_at, code, original_url, clicks
FROM short_urls
WHERE original_url LIKE $3
ORDER BY created_at ASC
OFFSET $1
LIMIT $2
`

type SearchParams struct {
	Offset      int32
	Limit       int32
	OriginalUrl string
}

func (q *Queries) Search(ctx context.Context, arg SearchParams) ([]ShortUrl, error) {
	rows, err := q.db.QueryContext(ctx, search, arg.Offset, arg.Limit, arg.OriginalUrl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShortUrl
	for rows.Next() {
		var i ShortUrl
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Code,
			&i.OriginalUrl,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
