// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"github.com/BlackestDawn/urlshortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIShorten creates a new instance of MockIShorten. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIShorten(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIShorten {
	mock := &MockIShorten{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIShorten is an autogenerated mock type for the IShorten type
type MockIShorten struct {
	mock.Mock
}

type MockIShorten_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIShorten) EXPECT() *MockIShorten_Expecter {
	return &MockIShorten_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockIShorten
func (_mock *MockIShorten) Delete(code string) error {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIShorten_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIShorten_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - code string
func (_e *MockIShorten_Expecter) Delete(code any) *MockIShorten_Delete_Call {
	return &MockIShorten_Delete_Call{Call: _e.mock.On("Delete", code)}
}

func (_c *MockIShorten_Delete_Call) Run(run func(code string)) *MockIShorten_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIShorten_Delete_Call) Return(err error) *MockIShorten_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIShorten_Delete_Call) RunAndReturn(run func(code string) error) *MockIShorten_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockIShorten
func (_mock *MockIShorten) GetStats(code string) (*domain.ShortUrl, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *domain.ShortUrl
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.ShortUrl, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.ShortUrl); ok {
		r0 = returnFunc(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ShortUrl)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIShorten_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockIShorten_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - code string
func (_e *MockIShorten_Expecter) GetStats(code any) *MockIShorten_GetStats_Call {
	return &MockIShorten_GetStats_Call{Call: _e.mock.On("GetStats", code)}
}

func (_c *MockIShorten_GetStats_Call) Run(run func(code string)) *MockIShorten_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIShorten_GetStats_Call) Return(shortUrl *domain.ShortUrl, err error) *MockIShorten_GetStats_Call {
	_c.Call.Return(shortUrl, err)
	return _c
}

func (_c *MockIShorten_GetStats_Call) RunAndReturn(run func(code string) (*domain.ShortUrl, error)) *MockIShorten_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockIShorten
func (_mock *MockIShorten) Resolve(code string) (string, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(code)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIShorten_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockIShorten_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - code string
func (_e *MockIShorten_Expecter) Resolve(code any) *MockIShorten_Resolve_Call {
	return &MockIShorten_Resolve_Call{Call: _e.mock.On("Resolve", code)}
}

func (_c *MockIShorten_Resolve_Call) Run(run func(code string)) *MockIShorten_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIShorten_Resolve_Call) Return(s string, err error) *MockIShorten_Resolve_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIShorten_Resolve_Call) RunAndReturn(run func(code string) (string, error)) *MockIShorten_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Shorten provides a mock function for the type MockIShorten
func (_mock *MockIShorten) Shorten(url string) (string, error) {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(url)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(url)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIShorten_Shorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shorten'
type MockIShorten_Shorten_Call struct {
	*mock.Call
}

// Shorten is a helper method to define mock.On call
//   - url string
func (_e *MockIShorten_Expecter) Shorten(url any) *MockIShorten_Shorten_Call {
	return &MockIShorten_Shorten_Call{Call: _e.mock.On("Shorten", url)}
}

func (_c *MockIShorten_Shorten_Call) Run(run func(url string)) *MockIShorten_Shorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIShorten_Shorten_Call) Return(s string, err error) *MockIShorten_Shorten_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIShorten_Shorten_Call) RunAndReturn(run func(url string) (string, error)) *MockIShorten_Shorten_Call {
	_c.Call.Return(run)
	return _c
}
