// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Create(url string) (*ShortUrl, error) {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ShortUrl
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*ShortUrl, error)); ok {
		return returnFunc(url)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *ShortUrl); ok {
		r0 = returnFunc(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ShortUrl)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - url string
func (_e *MockIRepository_Expecter) Create(url any) *MockIRepository_Create_Call {
	return &MockIRepository_Create_Call{Call: _e.mock.On("Create", url)}
}

func (_c *MockIRepository_Create_Call) Run(run func(url string)) *MockIRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_Create_Call) Return(shortUrl *ShortUrl, err error) *MockIRepository_Create_Call {
	_c.Call.Return(shortUrl, err)
	return _c
}

func (_c *MockIRepository_Create_Call) RunAndReturn(run func(url string) (*ShortUrl, error)) *MockIRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Delete(code string) error {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - code string
func (_e *MockIRepository_Expecter) Delete(code any) *MockIRepository_Delete_Call {
	return &MockIRepository_Delete_Call{Call: _e.mock.On("Delete", code)}
}

func (_c *MockIRepository_Delete_Call) Run(run func(code string)) *MockIRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_Delete_Call) Return(err error) *MockIRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Delete_Call) RunAndReturn(run func(code string) error) *MockIRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function for the type MockIRepository
func (_mock *MockIRepository) FindByCode(code string) (*ShortUrl, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *ShortUrl
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*ShortUrl, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *ShortUrl); ok {
		r0 = returnFunc(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ShortUrl)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockIRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - code string
func (_e *MockIRepository_Expecter) FindByCode(code any) *MockIRepository_FindByCode_Call {
	return &MockIRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", code)}
}

func (_c *MockIRepository_FindByCode_Call) Run(run func(code string)) *MockIRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_FindByCode_Call) Return(shortUrl *ShortUrl, err error) *MockIRepository_FindByCode_Call {
	_c.Call.Return(shortUrl, err)
	return _c
}

func (_c *MockIRepository_FindByCode_Call) RunAndReturn(run func(code string) (*ShortUrl, error)) *MockIRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementClicks provides a mock function for the type MockIRepository
func (_mock *MockIRepository) IncrementClicks(code string) error {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for IncrementClicks")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_IncrementClicks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementClicks'
type MockIRepository_IncrementClicks_Call struct {
	*mock.Call
}

// IncrementClicks is a helper method to define mock.On call
//   - code string
func (_e *MockIRepository_Expecter) IncrementClicks(code any) *MockIRepository_IncrementClicks_Call {
	return &MockIRepository_IncrementClicks_Call{Call: _e.mock.On("IncrementClicks", code)}
}

func (_c *MockIRepository_IncrementClicks_Call) Run(run func(code string)) *MockIRepository_IncrementClicks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_IncrementClicks_Call) Return(err error) *MockIRepository_IncrementClicks_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_IncrementClicks_Call) RunAndReturn(run func(code string) error) *MockIRepository_IncrementClicks_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIRepository
func (_mock *MockIRepository) List(page int, amount int, search string) ([]*ShortUrl, int, error) {
	ret := _mock.Called(page, amount, search)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*ShortUrl
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int, int, string) ([]*ShortUrl, int, error)); ok {
		return returnFunc(page, amount, search)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int, string) []*ShortUrl); ok {
		r0 = returnFunc(page, amount, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ShortUrl)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int, string) int); ok {
		r1 = returnFunc(page, amount, search)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = returnFunc(page, amount, search)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - page int
//   - amount int
//   - search string
func (_e *MockIRepository_Expecter) List(page any, amount any, search any) *MockIRepository_List_Call {
	return &MockIRepository_List_Call{Call: _e.mock.On("List", page, amount, search)}
}

func (_c *MockIRepository_List_Call) Run(run func(page int, amount int, search string)) *MockIRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIRepository_List_Call) Return(shortUrls []*ShortUrl, n int, err error) *MockIRepository_List_Call {
	_c.Call.Return(shortUrls, n, err)
	return _c
}

func (_c *MockIRepository_List_Call) RunAndReturn(run func(page int, amount int, search string) ([]*ShortUrl, int, error)) *MockIRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
